{{- if .Values.logstashConfig.features.syslog.enabled -}}
apiVersion: v1
kind: Service
metadata:
  name: {{ template "ingest.fullname" . }}-logstash
  namespace: default
  labels:
    app: {{ template "ingest.name" . }}-logstash
    component: logstash
spec:
  ports:
  - name: tcp
    protocol: TCP
    port: 5144
    nodePort: 30144
  - name: udp
    protocol: UDP
    port: 5144
    nodePort: 30144
  type: NodePort
  externalTrafficPolicy: Local
  selector:
    app: {{ template "ingest.name" . }}-logstash
    component: logstash
{{- end -}}
